spring:
  application:
    name: provider
server:
  port: 9091

dubbo:
  application:
    name: consumer
  registry:
    address: zookeeper://192.168.160.131:2181

  #protocol:
   # port: 2080
    #name: dubbo
  #provider:
   # timeout: 1000